<section id="questions" class="container-fluid">
	<div class="row">
		<div class="col-md-10">
			<h1>Questions</h1>
		</div>
		<div class="right-top-button col-md-2">
			<!-- Button trigger modal -->
			<button type="button" id="add_button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Ask Question
			</button>
		
		</div>	
	</div>
	<div class="row data-search question-search">
		<form action="#" class="col-md-12">		
		    <input type="search" class="form-control" placeholder="Question or #tag" />
		    <button type="submit" class="btn btn-primary" value="">
		    	<span class="glyphicon glyphicon-search"></span>
		    </button>
		    <button class="btn btn-default" value="">
		    	<span class="fa fa-wrench"></span>
		    </button>
		</form>
	</div>


	<h1>Popular Tags</h1>
	<div class="row questions-tags">
		<span class="tag col-md-1">#cdi</span>
		<span class="tag">#oil</span>
		<span class="tag col-md-4">#lpg</span>
		<span class="tag">#first_contract</span>
		<span class="tag col-md-3">#job</span>
		<span class="tag col-md-1">#offshore</span>
		<span class="tag">#promotion</span>
		<span class="tag">#port_state_control</span>
		<span class="tag col-md-1">#psc</span>
		<span class="tag">#heavy weather</span>
		<span class="tag col-md-1">#job</span>
		<span class="tag">#offshore</span>
		<span class="tag col-md-1">#promotion</span>
		<span class="tag">#oil</span>
		<span class="tag col-md-3">#lpg</span>
		<span class="tag">#first_contract</span>
		<span class="tag col-md-1">#job</span>
		<span class="tag">#offshore</span>
	</div> <!-- row questions-tags -->


	<div class="questions-list">
		<h1>Latest Questions</h1>
		<div class="row data-block questions-entry">
			<ul class="pe-social col-md-1 social-labels">
			  <li><a href="#0"><i class="pe-so-facebook pe-bg pe-hover  pe-2x"></i></a></li>
			  <li><a href="#0"><i class="pe-so-vk pe-bg pe-hover  pe-2x"></i></a></li>
			  <li><a href="#0"><i class="pe-so-linkedin pe-bg pe-hover  pe-2x"></i></a></li>
			</ul>
			<div class="col-md-10">
				<div class="row">
					<div class="drop-shadow col-md-12">
						<div class="row">
							<div class="col-md-2 data-avatar">
								<img src="/_temp/friend1.png" />
								<h4>Katrin Mangiel</h4>
							</div>
							<div class="col-md-10">
								<div class="row data-text">
									<div class="col-md-12 ">
										<h3>How to prepare for CDI inspection ?</h3>
										<p>This is Photoshop's version  of Lorem Ipsum. nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. aliquam massa nisl quis neque. Suspendisse in orci enim.</p>									
									</div>
								</div>

								<div class="row data-pics">
								</div>
								<div class="row data-actions">
									<div class="col-md-8 questions-tags">
										<span class="tag">#drill</span>
										<span class="tag">#brake_lining</span>
										<span class="tag">#arrival</span>
										<span class="tag">#fitter</span>
										<span class="tag">#drill</span>
										<span class="tag">#brake_lining</span>
										<span class="tag">#arrival</span>
										<span class="tag">#fitter</span>
										<span class="tag">#drill</span>
										<span class="tag">#brake_lining</span>
										<span class="tag">#arrival</span>
										<span class="tag">#fitter</span>
										<span class="tag">#drill</span>
										<span class="tag">#brake_lining</span>
										<span class="tag">#arrival</span>
										<span class="tag">#fitter</span>
										<span class="tag">#drill</span>
										<span class="tag">#brake_lining</span>
										<span class="tag">#arrival</span>
										<span class="tag">#fitter</span>
										<span class="tag">#drill</span>
										<span class="tag">#brake_lining</span>
										<span class="tag">#arrival</span>
										<span class="tag">#fitter</span>
									</div>
									<div class=" col-md-3">
										<button class="btn btn-primary" value="">
											<span class="fa fa-share"></span>
											Reply On Question
										</button>
									</div>
								</div>	 <!-- row job-actions -->										
							</div>
						</div>
					</div> <!-- -->
					<div class="activity-block  col-md-12">
						<div class="row">
							<div class="col-md-2 views">
								<span class="icon fa fa-eye"></span>
								<span class="count">3821</span>
							</div>
							<div class="col-md-2 comments">
								<a href="#">
									<span class="icon li_bubble icon-sm"></span>
									<span class="count">875</span>
								</a>
							</div>
							<div class="col-md-2 applied">
								<a href="#">
									<span class="icon fa fa-user"></span>
									<span class="count">138</span>
								</a>
							</div>

							<div class="col-md-2 time">
								<div>
									<span class="icon linea-basic-clock"></span>
									<span class="date">Yesterday</span>
								</div>
							</div>								
						</div>
					</div> <!-- activity-block  -->				
				</div> <!-- row  -->
			</div>
			<ul class="col-md-1 pe-social data-type">
			  <li class="question-type">
			  	<i class="li_study pe-2x"></i>
			  </li>
			</ul>				
		</div> <!-- row questions-entry -->

	</div> <!-- questions-list -->

</section>