<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title> << Login >> Seacontact Admin Module</title>
    
    
    
    
	 <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
	     ->appendStylesheet('/css/admin/login.css')
	 ;?>
    
    
    
  </head>

  <body>

    <div class="wrapper">
	<div class="container">
		<h1>Welcome</h1>
		
		<form class="form">
			<input type="text" placeholder="Username">
			<input type="password" placeholder="Password">
			<button type="submit" id="login-button">Login</button>
		</form>
	</div>
	
	<ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
</div>
	<?php $this->inlineScript()->prependFile($this->basePath('js/admin-login.js'))
	                           ->prependFile($this->basePath('js/jquery-2.1.3.min.js')); ?>
  </body>
</html>
