<section class="container-fluid">
	<?php
		$form = $this->form;
		$form->prepare();
		echo $this->form()->openTag($form);

	?>
		<?=$this->formElement($form->get('id'));?>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<div class="col-md-12">
						<?=$this->formLabel($form->get('name'));?>
						<?=$this->formElement($form->get('name')->setAttribute('class', 'form-control input-sm '));?>
						<?=$this->formElementErrors($form->get('name'));?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12">
						<?=$this->formLabel($form->get('description'));?>
						<?=$this->formElement($form->get('description')->setAttribute('class', 'form-control input-sm '));?>
						<?=$this->formElementErrors($form->get('description'));?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12">
						<?=$this->formButton()->openTag($form->get('submit')->setAttribute('class', 'btn btn-primary form-control input-sm'));?>
							<span class="fa fa-edit"></span> 
				 			 <?=$form->get('submit')->getLabel();?> 
						<?=$this->formButton()->closeTag();?>
					</div>
				</div>
			</div>
		</div>

	<?= $this->form()->closeTag();?>
</section>