<div class="row">
	<div class="col-md-12 table-responsive">
		<div class="box">
			<div class="box-header bg-info">
				<div class="col-md-2">
					<h4><?=$this->translate('Tags');?></h4>
				</div>
				<div class="col-md-10">
					<?=$this->partial('application/partial/active-filters-list');?>
				</div>
			</div>
			<div class="box-body">
				<table class="table table-bordered table-hover table-condensed table-favorites">
					<thead>
						<tr>
							<th>ID #</th>
							<th><?=$this->translate('Tag');?></th>
							<th><?=$this->translate('Section');?></th>
							<th><?=$this->translate('Description');?></th>
							<th><?=$this->translate('Count');?></th>
							<th class="text-center"><i class="fa fa-edit"></i></th>
							<th class="text-center"><i class="fa fa-trash"></i></th>
						</tr>
					</thead>
					<?php foreach($data_list as $data_item) {?>
						<tr>
							<td class="col-md-1"><?=$data_item->id;?></td>
							<td class="col-md-3">
								<?=$data_item->name;?>
							</td>
							<td class="col-md-2">
								<a href="<?=$this->url('admin/actions', ['controller' => 'content', 'action' => 'tags'], ['query' => ['filters' => ['section' => $data_item->section]]]);?>">
									<?=$data_item->section;?>
								</a>
							</td>
							<td class="col-md-3">
								<?=$data_item->description;?>
							</td>
							<td class="col-md-1">
								<?=$data_item->count;?>
							</td>
							<td class="col-md-1 text-center">
								<a class="edit_tag" data-id="<?=$data_item->id;?>" href="<?=$this->url('admin/actions', array('controller' => 'content', 'action' => 'edit-tag', 'id' => $data_item->id));?>" > 
									<span class="fa fa-edit"></span>
								</a>
							</td>
							<td class="col-md-1 text-center">
								<a class="delete_tag" data-id="<?=$data_item->id;?>" href="<?=$this->url('admin/actions', array('controller' => 'index', 'action' => 'delete'), array('query' => array(
														'id' => $data_item->id, 'section' => 'tag'
													)));?>" > 
									<span class="fa fa-trash"></span>
								</a>
							</td>
						</tr>
						
					<?php }?>
				</table>
			</div>
		</div>

	</div>

</div>
<div class="row">
	<div class="col-md-12 text-center">
		<?=$this->partial('application/partial/custom_pagination');?>
	</div>
</div>

<?=$this->partial('application/modal',array(
					'modal_name' => 'tag_modal',
					'modal_size' => 'md',
					'modal_title' => $this->translate('Edit Tag')
));?>
<?=$this->partial('application/js/load_content_ajax_submit', ['modal_name' => '#tag_modal']);?>

<script type="text/javascript">
	$('body').on('click', '.edit_tag', function(e){
		$('#tag_modal').modal('show');
		e.preventDefault();
		var url = $(this).attr('href');
		loadContent(url);
	});
</script>