
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls"  data-use-bootstrap-modal="false">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        <?=$this->translate('Previous');?>
                    </button>
                    <button type="button" class="btn btn-primary next">
                        <?=$this->translate('Next');?>
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
	
	$this->headScript()->appendFile('/vendor/blueimp/js/jquery.blueimp-gallery.min.js'._SCRIPTS_VER_);
	$this->headScript()->appendFile($this->basePath('vendor/bootstrap-image-gallery/js/bootstrap-image-gallery.min.js'._SCRIPTS_VER_));

	$this->headLink()->appendStylesheet('/vendor/blueimp/css/blueimp-gallery.min.css'._SCRIPTS_VER_);
	$this->headLink()->appendStylesheet($this->basePath('vendor/bootstrap-image-gallery/css/bootstrap-image-gallery.min.css'._SCRIPTS_VER_));

    // #error Cannot find this script in the web:
    // $this->headScript()->appendFile($this->basePath('vendor/grid-maker/grid-maker.js'._SCRIPTS_VER_));
    // $this->headLink()->appendStylesheet($this->basePath('vendor/grid-maker/style.css'._SCRIPTS_VER_));
?>
