<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/application.config.old
 */
return array(
    'modules' => array(
        'Dkim',
        'EdpModuleLayouts',
        'BitWeb\\CronModule',
        'ServiceLocatorFactory',
        'dompdfmodule',
        'AcMailer',
        'GoogleMapsTools',
        'GMaps',
        'ZF\\DevelopmentMode',
        'ZF\\Apigility',
        'ZF\\Apigility\\Provider',
        'ZF\\Apigility\\Documentation',
        'AssetManager',
        'ZF\\ApiProblem',
        'ZF\\Configuration',
        'ZF\\OAuth2',
        'ZF\\MvcAuth',
        'ZF\\Hal',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
        'ZFTool',
        'ZF\\Apigility\\Admin',
        'Application',
        'My',
        'Company',
        'UserInfo',
        'CompanyInfo',
        'Admin',
        'Api',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            '.',
            './module',
            './vendor',
            'GoogleMapsTools' => './vendor/sgoranov/google-maps-tools',
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
    ),
);
