<?php
	$page_url = $this->url('sc/logbook/actions', 
		array('action' => 'view', 'id' => $log_entry->id)
	);
	$author = zgetUserName($log_entry);
	$title = $this->translate('Logbook').' - '.$author.' : '.zshorterText(removeBrakes(strip_tags(html_entity_decode($log_entry->text))), 10);
	$keywords = $log_entry->tags;
	if(!$title) $title = $author;
	$description = '#'.zstripForHashTag($author).': '.zshorterText(strip_tags(html_entity_decode($log_entry->text)), 80)."\n\r".zmakeHashTagString($log_entry->tags);
	$default_img = zgetUserAvatar($log_entry);
	// meta tags for vkontakte:
	$this->headTitle()->prepend($title);
	$this->headMeta()->appendName('title', $title);
	$this->headMeta()->appendName('description', $description);
	$this->headMeta()->appendName('keywords', $keywords);

	//meta tags for facebook:
	$this->headMeta()->appendName('author', $author);
	$this->headMeta()->appendProperty('og:url', $page_url);
	$this->headMeta()->appendProperty('og:type', 'website');
	$this->headMeta()->appendProperty('og:title', $title);
	$this->headMeta()->appendProperty('og:keywords', $keywords);
	$this->headMeta()->appendProperty('og:description', $description);
	$this->headMeta()->appendProperty('og:author', $author);
	


	$pics = json_decode($log_entry->pics);

	if(isset($pics[0]->img) && file_exists(_PICSROOT_.$pics[0]->img)) {
		$image_url = _ADDRESS_._PICSWWW_.$pics[0]->img;
		$this->headLink(array('rel' => 'image_src', 'href' => $image_url), 'PREPEND');
		$this->headMeta()->appendProperty('og:image', $image_url);
	} else {
		$this->headMeta()->appendProperty('og:image', $default_img);
	}


;?>

<section id="news" class="container-fluid">
	<?php
		$this->layout()->show_breadcrumbs = true;
	?>
	<div class="row">
		<div class="col-md-12 data-list">
			<?php $log_entry->full_view = 1;?>
			<?=$this->partial('my/partial/logbook-item.phtml', $log_entry);?>
		</div>
	</div>
	<div class="row">
		<?php if ($this->isPermitted('application\controller\social.attach-wall-post')): ?>
			<div class="col-md-12">
				<?php $message = $this->translate('Attach Vk Post from Public');?>
				<?php if ($log_entry->post_vk_wall && $log_entry->post_vk_id): ?>
					<?php $message = $this->translate('Attach Other Post');?>
					<div class="row pb">
						<div class="col-md-4 col-md-offset-4 text-center">
							<i class="fa fa-vk bg-primary" style="padding: 0.2em;"></i>  <?=$this->translate('VK Post already attached');?>
						</div>
					</div>
				<?php endif ?>
				<div class="row pb">
					<div class="col-md-4 col-md-offset-4">
						<button type="button" class="btn btn-primary btn-sm form-control btn-responsive" data-toggle="modal" data-target="#vk_public_modal"> 	
							<i class="fa fa-vk fa-lg"></i> 
							<?=$message;?>
						</button>
					</div>
				</div>
			</div>
		<?php endif ?>
	</div>
	<div class="row">
		<?php $l_count = count($sim_logs);?>
		<?php if ($l_count): ?>
			<h4 class="text-muted"><b><?=$this->translate('Similar logbooks');?></b></h4>
			<hr />
			<?php foreach ($sim_logs as $logbook): ?>
				<?php if ($logbook->text && strlen($logbook->text) > 200): ?>
					<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
						<div class="row pb05">
							<div class="col-md-2 text-center">
								<?=$this->partial('my/partial/news-item-avatar.phtml', ['user_info' => $logbook, 'avatar_size' => 45, 'small_text' => 1]);?>
							</div>
							<div class="col-md-10">
								<p><?=zhtml_cut(strip_tags(htmlspecialchars_decode($logbook->text)), 100);?></p>
								<span class="pull-right small"><a href="<?=$this->url('sc/logbook/actions', ['action' => 'view', 'id' => $logbook->id]);?>" ><?=$this->translate('Read more');?></a></span>
							</div>
						</div>
					</div>
				<?php endif ?>

			<?php endforeach ?>
		<?php endif ?>
	</div>
</section>
<?=$this->partial('application/modal', ['modal_name' => 'vk_public_modal','modal_size' => 'md', 'modal_title' => $this->translate('Attach VK Post'),]);?>
<?=$this->partial('application/js/load_content_ajax_submit', ['modal_name' => '#vk_public_modal']);?>
<script type="text/javascript">
	$('#vk_public_modal').on('show.bs.modal', function (event) {
		loadContent('/social/attach-wall-post', {section: 'logbook', id: '<?=$log_entry->id;?>'});
	});
</script>
<?=$this->partial('application/image-gallery');?>
