<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-12 text-center">
				<?php 
					$container = $this->navigation('navigation')->findOneByResource($resource);
				?>	
					<div class="btn-group" role="group">
						<?php if ($container): ?>
						 	<button class="btn btn-success btn-lg">
						 		<?=strtoupper($container->getLabel());?>
						 	</button>
						<?php endif ?>
						<button class="btn btn-default btn-lg">
							<?=$resource;?>
						</button>
					</div>
				</div>
			</div>
			
			<div class="row">
				<?php $resource_object = $access->getResource($resource); ?>
				<ul class="col-md-3 list-unstyled text-left">
					<h4><?=$this->translate('Parent Resources');?></h4>
					<?php for ($i=0; $i < count($resources); $i++) : ?>
						<?php $parent_object = $access->getResource($resources[$i]);?>
						<?php if($access->inheritsResource($resource_object, $parent_object)) :?>
							<li>
								<?php 
									$container = $this->navigation('navigation')->findOneByResource($resources[$i]);
								?>
								<div class="btn-group" role="group">
									<a href="<?=$this->url('admin/actions', ['controller' => 'access', 'action' => 'resource'], ['query' => ['resource' => $resources[$i]]]);?>">
									<?php if ($container): ?>
									 	<button class="btn btn-success btn-sm">
									 		<?=strtoupper($container->getLabel());?>
									 	</button>
									<?php endif ?>
										<button class="btn btn-default btn-sm">
										<?=$resources[$i];?>
										</button>
									</a>
								</div>

							</li>
						<?php endif ?>
					<?php endfor ?>
				</ul>
				<ul class="col-md-3 list-unstyled text-left">
					<h4><?=$this->translate('Child Resources');?></h4>
					<?php for ($i=0; $i < count($resources); $i++) : ?>
						<?php $child_object = $access->getResource($resources[$i]);?>
						<?php if($access->inheritsResource($child_object, $resource_object)) :?>
							<li>
							<?php 
								$container = $this->navigation('navigation')->findOneByResource($resources[$i]);
							?>
							<div class="btn-group" role="group">
								<a href="<?=$this->url('admin/actions', ['controller' => 'access', 'action' => 'resource'], ['query' => ['resource' => $resources[$i]]]);?>">
								<?php if ($container): ?>
								 	<button class="btn btn-success btn-xs">
								 		<?=strtoupper($container->getLabel());?>
								 	</button>
								<?php endif ?>
									<button class="btn btn-default btn-xs">
									<?=$resources[$i];?>
									</button>
								</a>
							</div>
							</li>
						<?php endif ?>
					<?php endfor ?>
				</ul>
				<ul class="col-md-3 list-unstyled text-center">
				<h4><?=$this->translate('Roles Having Access');?></h4>
				<?php for ($i=0; $i < count($roles); $i++) : ?>
					<?php if($this->access->isAllowed($roles[$i], $resource)) :?>
						<li>
							<a href="<?=$this->url('admin/actions', ['controller' => 'access', 'action' => 'roles'], ['query' => ['filter' => $roles[$i]]]);?>">
								<button class="btn btn-default btn-sm form-control">
									<span class="fa fa-user" aria-hidden="true"></span> <?=$roles[$i];?>
								</button>
							</a>
						</li>
					<?php endif ?>
				<?php endfor ?>
				</ul>
				<ul class="col-md-3 list-unstyled text-center">
				<h4><?=$this->translate('Roles Dont Having Access');?></h4>
				<?php for ($i=0; $i < count($roles); $i++) : ?>
					<?php if(!$this->access->isAllowed($roles[$i], $resource)) :?>
						<li>
							<a href="<?=$this->url('admin/actions', ['controller' => 'access', 'action' => 'roles'], ['query' => ['filter' => $roles[$i]]]);?>">
								<button class="btn btn-default btn-sm form-control">
									<span class="fa fa-user" aria-hidden="true"></span> <?=$roles[$i];?>
								</button>
							</a>
						</li>
					<?php endif ?>
				<?php endfor ?>
				</ul>
			</div>

		</div>
	</div>
</div>