<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-12 text-center">
					<div class="btn-group" role="group">
						<button class="btn btn-default btn-lg">
							<?=$role;?>
						</button>
					</div>
				</div>
			</div>
			
			<div class="row">
				<?php $role_object = $access->getRole($role); ?>
				<ul class="col-md-3 list-unstyled text-left">
					<h4><?=$this->translate('Parent Roles');?></h4>
					<?php for ($i=0; $i < count($roles); $i++) : ?>
						<?php $parent_object = $access->getRole($roles[$i]);?>
						<?php if($access->inheritsRole($role_object, $parent_object)) :?>
							<li>
								<a href="<?=$this->url('admin/actions', ['controller' => 'access', 'action' => 'role'], ['query' => ['role' => $roles[$i]]]);?>">
									<button class="btn btn-default btn-sm form-control">
									<?=$roles[$i];?>
									</button>
								</a>
							</li>
						<?php endif ?>
					<?php endfor ?>
				</ul>
				<ul class="col-md-3 list-unstyled text-left">
					<h4><?=$this->translate('Child Roles');?></h4>
					<?php for ($i=0; $i < count($roles); $i++) : ?>
						<?php $child_object = $access->getRole($roles[$i]);?>
						<?php if($access->inheritsRole($child_object, $role_object)) :?>
							<li>
								<a href="<?=$this->url('admin/actions', ['controller' => 'access', 'action' => 'role'], ['query' => ['role' => $roles[$i]]]);?>">
									<button class="btn btn-default btn-sm form-control">
									<?=$roles[$i];?>
									</button>
								</a>
							</li>
						<?php endif ?>
					<?php endfor ?>
				</ul>
			</div>

		</div>
	</div>
</div>