<section classs="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="box">
				<div class="box-header bg-info">
					<div class="row">
						<div class="col-md-2"><h4><?=$this->translate('Bugs');?></h4></div>
						<div class="col-md-9 text-center">
						</div>
					</div>
				</div>
				<div class="box-body table-responsive">
					<table class="table table-bordered table-hover table-condensed table-favorites">
						<thead>
							<tr>
								<th class="col-md-1"><?=$this->translate('Time');?></th>
							</tr>
						</thead>
						<?php foreach($data_list as $item):?>
							<tr>
								<td><?=zformatDateTime($item->time);?></td>
							</tr>			
						<?php endforeach ?>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
	<div class="col-md-12 text-center">
		<?=$this->partial('application/partial/custom_pagination');?>
	</div>
	</div>
</section>