<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;

$maxDepth = $this->navigation($container)->getMaxDepth();
$minDepth = $this->navigation($container)->getMinDepth();

// create iterator
// $iterator = new \RecursiveIteratorIterator(
//     $container,
//     \RecursiveIteratorIterator::SELF_FIRST
// );

// if (is_int($maxDepth)) {
//     $iterator->setMaxDepth(0);
// }


?>
<ul class="<?php echo $this->navigation($container)->menu()->getUlClass(); ?>">
    <li class="header"><?=$this->translate('ADMIN MENU');?></li>
    <?php foreach ($container as $page): ?>
    <?php  //$depth = $iterator->getDepth(); ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <li<?php if ($page->isActive()) echo ' class="active"' ?>>
                <a 
                    class="nav-header" 
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>
                    >
                    <?php if ($page->get("icon") !== ""): ?>
                        <span class="<?php echo $page->get("icon"); ?> icon"></span>
                    <?php endif; ?>
                    <span class="link_text">
                        <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                    </span>
                    <?php if ($page->get("notifications") != ""): ?>
                        <span class="notification"><?php echo $page->get("notifications");?></span>
                    <?php endif; ?>
                </a>
            </li>
        <?php else: ?>
            <?php
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) :
                ?>
                <li class="treeview <?php if ($page->isActive(true)) echo ' active' ?>">
                    <a  href="<?= $page->getHref();?>">
                        <?php if ($page->get("icon") !== ""): ?>
                            <span class="<?php echo $page->get('icon'); ?> icon"></span>
                        <?php endif; ?>
                        <span class="link_text">
                            <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                        </span> <i class="fa fa-angle-left pull-right"></i>
                        <?php if ($page->get("notifications") != ""): ?>
                            <span class="notification"><?php echo $page->get("notifications");?></span>
                        <?php endif; ?>
                    </a>
                    <ul class="treeview-menu">
                        <?php foreach ($page->getPages() as $child): ?>
                            <?php if ($maxDepth == 0 || !$this->navigation()->accept($child)) continue; ?>
                            <?php if ($child->get("separator") === true): ?>
                                <li class="divider"></li>
                                    <?php
                                    continue;
                                endif;
                                ?>
                            <li<?php if ($child->isActive()) echo ' class="active"' ?>>
                                <a 
                                    href="<?php echo $child->getHref() ?>"
                                    <?php if ($child->getTarget() != ""): ?>
                                        target="<?php echo $child->getTarget(); ?>"
                                    <?php endif; ?> >
                                        <?php if ($child->get("icon") !== ""): ?>
                                        <span class="<?php echo $child->get("icon"); ?> icon"></span>
                                    <?php endif; ?>
                                    <span class="link_text">
                                        <?php echo $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                                    </span>
                                    <?php if ($child->get("notifications") != ""): ?>
                                        <span class="notification"><?php echo $child->get("notifications");?></span>
                                    <?php endif; ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </li>   
            <?php endif; ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>