<?php

 if(!isset($user_id)) $user_id = $user['user_id'];
 if(!isset($text)) $text = $this->translate('Add To Contacts');
 if(!isset($class)) $class = '';

?>

<a href="<?= $this->url('sc/contacts/actions', array(
						'action' => 'add',
						'id' => $user_id
						)); ?>" data-action="contacts" title="<?=$this->translate('Add to Friends');?>" >
	<button type="button" class="btn btn-xs btn-primary <?=$class;?>" >
		<span class="glyphicon glyphicon-link"></span> <?=$text;?>
	</button>
</a>