<div class="loading-fixed hide"></div>
<div id="edit_window" class="row hide">
  	<div id="selection_area" class="col-md-9">
  	</div>
  	<div id="edit_preview" class="col-md-3">
			<div id="preview_big" class="hide" style="overflow: hidden;">
				<img src="<?=_IMGWWW_._AVABLANKUSER_;?>" style="width: 180px; height: 270px;" id="avatar_big" />
			</div>
			<div id="preview_small" class="hide" style="overflow: hidden;">
				<img src="<?=_IMGWWW_._AVABLANKUSER_;?>" style="width: 100px; height: 100px;" id="avatar_small" />
			</div>
			<div class="pull-right">
				<br />
			</div>
  		<form name="thumbnail">
  			<input type="hidden" name="x1" value="" id="x1" />
  			<input type="hidden" name="y1" value="" id="y1" />
  			<input type="hidden" name="x2" value="" id="x2" />
  			<input type="hidden" name="y2" value="" id="y2" />
  			<input type="hidden" name="w" value="" id="w" />
  			<input type="hidden" name="h" value="" id="h" />
  		</form>
  	</div>
</div>