apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-depl-api
  labels:
    env: development
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: sc-proj-api
  template:
    metadata:
      labels:
        project: sc-proj-api
    spec:
      volumes:
        - name: static
          emptyDir: { }
      containers:
        - name: sc-api
          image: zzzloy777/sc:latest
          env:
            - name: _MYSQL_HOST_
              value: sc-serv-db
            - name: _MYSQL_DB_NAME_
              value: "seacontact"
            - name: _MYSQL_USER_
              value: "root"
            - name: _MYSQL_PASSWORD_
              value: "cr3wsilent"
            - name: _REDIS_IP_
              value: "scredis"
            - name: _REDIS_PORT_
              value: "6379"
            - name: _GMAPS_KEY_
              value: "AIzaSyB3CTEkTrIuXKfRQgqZ2d1qosplkot-zN0"
            - name: _DKIM_DOMAIN_
              value: "seacontact.com"
            - name: _DKIM_KEY_
              value: "MIICXAIBAAKBgQC2cyK+3vewbvHUmJfCaA1gzLdqyaNg6Vm5k2JkAEpmaYgtiDzy2379nMxJw7zSvexiXPuDa5IrNFUXvaszKuFfugFxTUFadmrXL3aW91Yh188WjawN7Z3GjK6QRhZ2U8ae28s7Zbrt7iDsDhseBUGgXDEXgIZBmZfBUoCVeKBUtQIDAQABAoGAKsFkfRJHPSNirI1t0vMLX4nZ2b6S+Nz2V9TAE+s1hDZq4TCyB7+ETO53uTmTgFddk9dyYWPOBy3mWv/ppL4BvkUjQUOdBtReus06B4tXVS0PWvs9FUndLMeJ7dV8GNfSEHbUa3Xu8fM2oyy59udEzPOM0k3QCcgQxlSHBwNElakCQQDyh1lJ7bdQqc4VhX2A0ARr9j12xgux6A2BrkN45lnivnG9+pJyx0ytSTAca6TIkF4bmJ3K5/0iHkIhyY0idCRvAkEAwJV9nJvFy53HMYfwiOliylm7E10VBRhTLzo3zv1EA8Tt7Tozwt86q64fTQuGaxHvM8w3ylCyi8SZmvkMf7fTGwJAFrfdAlLVOCYf2t49SmKx91cCnOyiTdD56urjASE6zEWgq/Yb38qRgS345sCil/MGDbm3Fjmy+Y4yDa4unUqZ2wJAB62uLXFUiJLI32OxJnRPuQus1s/OR765ileC5CDa9l+CsQOyDqIB39h4bQT5nglABUuuKcXf6Iy1JyWo5uq4YwJBAIa0h2iTF02yJ2FRHJ+R/1MzmglPIwPowdTDRd3eKCkIdC5VFD1LB5u1hVX2Fs+EuzkBSSe3lEUBvcB0WhmXKUo="
            - name: _MBOFFICE_
              value: "office@seacontact.com"
            - name: _MBOFFICEPWD_
              value: "scoffice01"
            - name: _MBCREW_
              value: "crew@seacontact.com"
            - name: _MBCREWPWD_
              value: "sccrew01"
            - name: _IN_APP_ID_
              value: "77z0oq1xmbw13v"
            - name: _IN_APP_SECRET_
              value: "hkvKjq1Q5sjr5H4Z"
            - name: _FB_APP_ID_
              value: "956454421068622"
            - name: _FB_APP_SECRET_
              value: "55b2859dd72711cb35c3a4f6a046e52b"
            - name: _VK_APP_ID_
              value: "5148062"
            - name: _VK_APP_SECR_KEY_
              value: "vaUa5LHfyics8QmgGcOf"
            - name: _VK_APP_CODE_
              value: "b926aafffea0bc3722"
            - name: _VK_2APP_ID_
              value: "5148067"
            - name: _VK_2APPSECR_KEY_
              value: "3Wu8bEsNZSC5cyr1evFH"
            - name: _VK_USER_
              value: "36868560"
            - name: _VK_USER_SECRET_
              value: "c6831373edaaeea6ce"
            - name: _VK_USER_TOKEN_
              value: "2fdfb83a7befde0e30e28b76e365b01cb3be2fcd10e2cebb26f6e57c451a41ce20bb538e9dc68464bf5a7"
            - name: _VK_GROUP_
              value: "101763341"
          volumeMounts:
            - mountPath: /var/www/html
              name: static
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /home/seacontact/. /var/www/html"]
        - name: nginx
          image: zzzloy777/sc-nginx
          ports:
            - containerPort: 80
              name: sc-nginx-80
            - containerPort: 443
              name: sc-nginx-443
          env:
            - name: PHP_FPM_HOST
              value: "127.0.0.1"
            - name: NGINX_PHP_SOURCE
              value: "/var/www/html"
            - name: NGINX_HOST
              value: "seacontact.com"
            - name: SSL_CERT_HOST
              value: "seacontact.com"
          volumeMounts:
            - mountPath: /var/www/html
              name: static
---
apiVersion: v1
kind: Service
metadata:
  name: sc-serv-api
  labels:
    env: development
spec:
  selector:
    project: sc-proj-api
  type: NodePort
  ports:
    - name: nginx80
      port: 80
      targetPort: 80
    - name: nginx443
      port: 443
      targetPort: 443
