<li class="dropdown messages-menu" data-section="mail">
  <!-- Menu toggle button -->
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-envelope-o"></i>
    <?php $count_notifications = count($section_notifications);?>
    <?php if ($count_notifications > 0): ?>
      <span class="label label-success not_label">
        <?=$count_notifications;?>
      </span>
    <?php endif ?>
  </a>
  <ul class="dropdown-menu">
    <li class="header">
      <?=$this->translate('You have');?> 
      <?=$count_notifications;?> 
      <?=$this->translate('notifications for mails');?>
    </li>
    <li>
      <ul class="menu">
        <?php if ($count_notifications > 0): ?>
            <?php foreach ($section_notifications as $notification): ?>
            <li class="notification_item container-fluid">
              <div class="row" style="margin-top: 2px; background-color: #F6F6F6;">
                <div class="col-xs-2 text-center pt">
                  <a href="<?=$this->url('admin/actions', array('controller' => 'mailbox' ,'action' => 'view', 'id' => $notification['not_section_id']));?>">
                    <button type="button" class="btn btn-xs btn-info" >
                      <i class="fa fa-envelope-o"></i>
                    </button>
                  </a>
                </div>
                <div class="col-xs-10">
                    <h6>
                      <small <?php if($notification['mail_box'] == _MBOFFICE_) :?> class="text-danger" <?php endif?> >
                        <b><?=$notification['mail_box'];?></b>
                      </small> 
                        <?=zformatDateTime($notification['time']);?>
                    </h6>
                    <a href="<?=$this->url('admin/actions', array('controller' => 'mailbox' ,'action' => 'view', 'id' => $notification['not_section_id']));?>">
                      <?php if ($notification['name'] || $notification['full_name'] || $notification['company_name']): ?>
                        <h6 class="text-info">         
                         <?=zgetUserName($notification);?>
                        </h6>
                      <?php endif ?>
                      <h5><?=$notification['not_message'];?></h5>
                    </a>
                </div>
              </div>
            </li> 
          <?php endforeach ?>
        <?php endif ?>
       
      </ul><!-- /.menu -->
    </li>
    <?php if ($count_notifications > 0): ?>
    <li class="footer clear_notif">
      <a href="#">
        <button class="btn btn-success btn-xs">
          <i class="glyphicon glyphicon-ok"></i>
          <?=$this->translate('Clear Mail Notifications');?>
        </button>
      </a>
    </li>
    <?php endif ?>
  </ul>
</li>