<div class="row">
	<div class="col-md-12">
		<?php foreach ($q_options['filters'] as $key => $value) :?>
			<?php if ($form->get('filters')->has($key)): ?>
				<?php $label = $form->get('filters')->get($key)->getLabel();?>
				
				<?php if (is_array($value)): ?>
					<?php for ($i=0; $i < count($value); $i++) :?>
						<?=$this->partial('admin/partial/filter-button', ['filters' => $q_options['filters'], 'label' => $label, 'value' => $value[$i], 'key' => $key]);?>
					<?php endfor;?>

				<?php else: ?>
					<?=$this->partial('admin/partial/filter-button', ['filters' => $q_options['filters'], 'label' => $label, 'value' => $value]);?>
				<?php endif ?>
			<?php endif ?>
		<?php endforeach;?>
		<?php if(!empty($q_options['filters']) && $q_options['layout'] == 'list') {?>
			<a href="<?=$this->routeMatch()->getUrl();?>">
				<button type="button" class="btn btn-xs btn-danger" aria-label="<?=$this->translate('Remove Filters');?>" >
				  <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span> <?=$this->translate('Remove Filters');?>
				</button>
			</a>
		<?php }?>
	</div>
</div>