<div class="alert alert-warning">
	<h4 class="text-center"><?=$this->translate('How to answer on questions');?></h4>
	<ul>
		<li><b><?=$this->translate('Please be sure to answer the question. Provide details and share your research!');?></b></li>
	</ul>
	<h5><?=$this->translate('But <i>avoid</i>');?></h5>
	<ul>
		<li class="pb"><?=$this->translate('Asking for help, clarification, or responding to other answers.');?></li>
		<li class="pb"><?=$this->translate('Making statements based on opinion; back them up with references or personal experience.');?></li>
		<li><?=$this->translate('All of us have some experience in something, but nobody can know everything. Be patient and keep positive attitude.');?></li>
	</ul>
</div>