<div class="row">
	<div class="col-md-12">
		<a href="<?=$this->url('sc/vk_oauth');?>">
		<button class="btn btn-xs btn-primary mt login_vk" > <i class="fa fa-vk"></i> Vkontakte </button>
		</a>
	</div>
	<div class="col-md-12">
		<a href="<?=$this->url('sc/fb_oauth');?>">
		<button class="btn btn-xs btn-info mt login_fb" > <i class="fa fa-facebook fa-lg"></i> Facebook </button>
		</a>
	</div>
	<div class="col-md-12">
		<a href="<?=$this->url('sc/in_oauth');?>">
		<button class="btn btn-xs btn-primary mt login_fb" > <i class="fa fa-linkedin"></i> LinkedIn </button>
		</a>
	</div>
</div>
