<span class="help-block bg-warning pt pb">
    <?=$this->translate('Still not with us ?');?> 
     <br /> 
     <a href="<?=$this->url('sc/fast-reg');?>">
         <strong><?=$this->translate('Register');?></strong>
     </a>
     <br /> 
   <?=$this->translate('Maybe I\'m in database ?');?> / <?=$this->translate('Forgot Password ?');?> 
    <br /> 
    <a href="<?=$this->url('sc/forgot-password');?>">
        <strong><?=$this->translate('Restore password');?></strong>
    </a>
</span>