<li class="share share_facebook" title="<?=$this->translate('share in');?> Facebook">
	<i class="pe-so-facebook pe-bg pe-hover pe-2x" data-url="<?=$page_url;?>"></i>
</li>
<li class="share" title="<?=$this->translate('share in');?> Vkontakte">
	<script type="text/javascript">
		document.write(VK.Share.button({url: "<?=$page_url;?>"},{type: "custom", text: "<img src=\"http://vk.com/images/share_32_eng_2x.png\" width=\"40\" height=\"40\" />", eng: 1}));
	</script>
</li>
<li class="share share_linkedin" title="<?=$this->translate('share in');?> LinkedIn">
	<i class="pe-so-linkedin pe-bg pe-hover pe-2x" data-url="<?=$page_url;?>"></i>
</li>
<!-- <li style="padding-bottom: 5px; width: 39px; text-align: center;" title="<?=$this->translate('Share in social networks');?>">
	<i class="fa fa-bullhorn text-muted" style="font-size: 9px;" ></i>
</li> -->