<div class="col-md-12  tags_list">
	<div class="well well-sm mb05 ">
		<div class="row ">
			<div class="col-md-12 text-center " >
				<h5 class="mt01 mb05 text-center"><strong><?=$this->translate('Popular #Tags');?></strong> <br /><small>*<?=$this->translate('Just click');?>*</small></h5>
				  <?php foreach ($tags_map as $tag): ?>
				  	<a href="#"  title="<?=$tag['description'].' ('.$tag['count'].')';?>" >
						<button class="btn btn-xs btn-default m02 token"><?=$tag['name'];?></button>
				  	</a>
				  <?php endforeach ?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$('.tags_list').on('click', '.token', function(e){
		e.preventDefault();
		$('#tags').tokenfield('createToken', $(this).text());
	});
</script>