<?php

$header = $this->translate('Registration on').' '._ADDRESS_NO_SLASH_.' '.$this->translate('successfully completed!');
$text1 = array( 
				$this->translate('Dear , sir').' '.$this->name,
				$this->translate('Registration successfully completed on').' '._ADDRESS_NO_SLASH_.', '.$this->translate('you can now enter the site with login'),
				'<h3>'.$this->login.'</h3>',
				$this->translate('And password'),
				'<h3>'.$this->password.'</h3>',
				$this->translate('on the'),
				
			);
$btn_link = $this->login_page;
$btn_text = $this->translate('Login page');

$text2 = array(
			$this->translate('Thank you for your registration on').' '._ADDRESS_NO_SLASH_,
		);

$footer = $this->translate('If you didn\'t attempt to register on').' '._ADDRESS_NO_SLASH_.' '.$this->translate('please ignore this email');

?>
<?=$this->partial('application/partial/mails/default_template', array('header' => $header, 'text1' => $text1, 'btn_link' => $btn_link, 'btn_text' => $btn_text, 'text2' => $text2, 'footer' => $footer ));?>
