<?php

$header = $this->translate('Confirm registration on').' '._ADDRESS_NO_SLASH_;
$text1 = array( 
				$this->translate('Dear , sir').' '.$this->name,
				$this->translate('To complete registration on').' '._ADDRESS_NO_SLASH_.', '.$this->translate('please follow the below link')
			);
$btn_link = $this->confirm_link;
$btn_text = $this->translate('Confirm registration');

$text2 = array(
			$this->translate('Or enter code'),
			'<h3>'.$this->confirm_code.'</h3>',
			$this->translate('on the').'<a href="'.$this->confirm_page.'">'.$this->translate('Confirmation page')
		);

$footer = $this->translate('If you didn\'t attempt to register on').' '._ADDRESS_NO_SLASH_.' '.$this->translate('please ignore this email');

?>
<?=$this->partial('application/partial/mails/default_template', array('header' => $header, 'text1' => $text1, 'btn_link' => $btn_link, 'btn_text' => $btn_text, 'text2' => $text2, 'footer' => $footer ));?>
