<div style="width: 100%;">
	<div style="width: 100%;text-align: center;">
		<a href="<?=_ADDRESS_.zgetUserLogin($user_info).'/cv';?>">
			<img src="<?=zgetUserAvatar($user_info);?>" style="height: 150px; padding-top: 1em;" />
			<h4><?=zgetUserName($user_info);?></h4>
		</a>
	</div>
	<?php if (count($experience_info) > 0): ?>
		<div style="width: 100%;">
			<h4 style="text-align: center;"><?=$this->translate('User experience');?>:</h4>
			<table class="table table-striped table-bordered table-experience">
				<thead>
					<tr>
						<th>#</th>
						<th>Ship Name</th>
						<th>Type</th>
						<th>Flag</th>
						<th>DWT</th>
						<th>Rank</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($experience_info as $count => $contract) {?>
						<tr>
							<th style="padding:10px;"><?=$count+1;?></th>
							<td style="padding:10px;"><?=$contract['ship_name'];?></td>
							<td style="padding:10px;"><?=$contract['ship_type'];?></td>
							<td style="padding:10px;"><?=$contract['flag'];?></td>
							<td style="padding:10px;"><?=$contract['dwt'];?></td>
							<td style="padding:10px;"><?=$contract['rank'];?></td>
						</tr>					
					<?php }?>
				</tbody>
			</table>
		</div>
	<?php endif ?>
</div>
<div style="clear:both;">
</div>