
<?= $this->doctype(); ?>
<html>
  <head>

	<meta charset="utf-8">
	<meta name="description" content="SEACONTACT / Admin page" />
	<meta name="author" content="z_loy" />

   <?= $this->headTitle('SEACONTACT '. $this->translate('ADMIN PAGE'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Styles -->
    <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
        ->prependStylesheet('/vendor/animate.css/animate.css')
        ->prependStylesheet('/css/fonts/ionicons/css/ionicons.min.css')
        ->prependStylesheet('/css/admin/skins/_all-skins.min.css')
        ->prependStylesheet('/css/admin/AdminLTE.css')
        ->prependStylesheet('/css/fonts/font-awesome/css/font-awesome.css')
        ->prependStylesheet('/vendor/twbs/bootstrap/dist/css/bootstrap.min.css')


        ->appendStylesheet('/vendor/chosen/chosen.min.css')
        ->appendStylesheet('/css/admin/main.css'._SCRIPTS_VER_)
        ->appendStylesheet('/css/content-main-default.css'._SCRIPTS_VER_)


    ;?>
    <!-- Theme style -->
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->

    <?= $this->headStyle();?>

    <!-- Scripts -->
    <?= $this->headScript()
    // ->appendFile($this->basePath('js/admin/plugins/slimScroll/jquery.slimscroll.min.js')) // what is that ?
    // ->appendFile($this->basePath('js/admin/plugins/fastclick/fastclick.min.js')) // what is that ?
    // ->appendFile($this->basePath('/js/admin/dist/app.min.js')) // menu not working

      ->prependFile($this->basePath('/vendor/bootstrap-notify/bootstrap-notify.min.js'))
      ->prependFile($this->basePath('/vendor/twbs/bootstrap/dist/js/bootstrap.min.js'))
      ->prependFile($this->basePath('/js/jquery-2.1.3.min.js'))

      ->appendFile('/vendor/chosen/chosen.jquery.js')
      ->appendFile($this->basePath('/js/admin-app.js'))
      ->appendFile($this->basePath('/js/admin/main.js'._SCRIPTS_VER_))
    ;?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body class="skin-blue">
    <div class="wrapper">

      <!-- Main Header -->
      <header class="main-header">

        <!-- Logo -->
        <a href="<?=_ADMINADRESS_;?>" class="logo"><b>SC</b>ADMIN</a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only"><?=$this->translate('Toggle navigation');?></span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <?php if ($this->isPermitted('admin\controller\tasks.view')): ?>
                <?php  $tasks_notif = $this->notifications()->tasks;?>
                <?=$this->partial(
                  'admin/partial/menu-notifications.phtml', 
                  array(
                        'menu_icon' => 'fa fa-bolt',
                        'section_notifications' =>  $tasks_notif,
                        'section_comment' => $this->translate('Tasks notifications'),
                        'section' => \Application\Model\AdminNotifTable::NOT_SECTION_ADMIN_TASK,
                        'sub_sections' => array(
                          array(
                            'item_type' => 'task',
                            'item_notifications' => array_filter($tasks_notif, function($i) {
                                                      if($i['not_section'] == \Application\Model\AdminNotifTable::NOT_SECTION_ADMIN_TASK) return true;
                                                      return false;
                                                    }),
                            'item_header_icon' => 'fa fa-bolt',
                            'item_header_text' => $this->translate('notifications on task activity'),
                            ),

                          )
                       )
                );?>
              <?php endif ?>
              <?php if ($this->isPermitted('admin\controller\mailbox')): ?>
                  <?=$this->partial('admin/partial/menu-mails.phtml',array('section_notifications' =>  $this->notifications()->mail));?>
                  <?php  $crewing_notif = $this->notifications()->crewing;?>
                  <?=$this->partial(
                    'admin/partial/menu-notifications.phtml', 
                    array(
                          'menu_icon' => 'fa fa-copyright',
                          'section_notifications' =>  $crewing_notif,
                          'section_comment' => $this->translate('notifications for Seacontact Crewing'),
                          'section' => 'crewing',
                          'sub_sections' => array(
                            array(
                              'item_type' => 'vacancy',
                              'item_notifications' => array_filter($crewing_notif, function($i) {
                                                        if($i['not_type'] == 'assign_candidate') return true;
                                                        return false;
                                                      }),
                              'item_header_icon' => 'glyphicon glyphicon-fire text-aqua',
                              'item_header_text' => $this->translate('new user assigned to vacancy'),
                              ),
                            array(
                              'item_type' => 'user',
                              'item_notifications' => array_filter($crewing_notif, function($i) {
                                                        if($i['not_type'] == 'assign_status') return true;
                                                        return false;
                                                      }),
                              'item_header_icon' => 'fa fa-user-plus text-aqua',
                              'item_header_text' => $this->translate('user assign status changed'),
                              ),
                            array(
                              'item_type' => 'user',
                              'item_notifications' => array_filter($crewing_notif, function($i) {
                                                        if($i['not_type'] == 'admin_note') return true;
                                                        return false;
                                                      }),
                              'item_header_icon' => 'fa fa-edit text-aqua',
                              'item_header_text' => $this->translate('user note added'),
                              ),
                            )
                         )
                  );?>
              <?php endif ?>
              <?php if ($this->isPermitted('admin\controller\vacancies')): ?>
                <?php  $vacancy_notif = $this->notifications()->vacancy;?>
                <?=$this->partial(
                  'admin/partial/menu-notifications.phtml', 
                  array(
                        'menu_icon' => 'glyphicon glyphicon-fire',
                        'section_notifications' =>  $vacancy_notif,
                        'section_comment' => $this->translate('notifications for Vacancies'),
                        'section' => 'vacancy',
                        'sub_sections' => array(
                          array(
                            'item_type' => 'vacancy',
                            'item_notifications' => array_filter($vacancy_notif, function($i) {
                                                      if($i['not_type'] == 'subscribe_vacancy') return true;
                                                      return false;
                                                    }),
                            'item_header_icon' => 'glyphicon glyphicon-fire text-aqua',
                            'item_header_text' => $this->translate('new members subscribed to vacancy'),
                            ),
                          array(
                            'item_type' => 'vacancy',
                            'item_notifications' => array_filter($vacancy_notif, function($i) {
                                                      if($i['not_type'] == 'new_vacancy') return true;
                                                      return false;
                                                    }),
                            'item_header_icon' => 'glyphicon glyphicon-fire text-aqua',
                            'item_header_text' => $this->translate('new vacancy added'),
                            ),

                          )
                       )
                );?>
              <?php endif ?>
              <?php if ($this->isPermitted('admin\controller\userdb.user')): ?>
                <?php  $user_notif = $this->notifications()->user;?>
                <?=$this->partial(
                  'admin/partial/menu-notifications.phtml', 
                  array(
                        'menu_icon' => 'glyphicon glyphicon-user',
                        'section_notifications' =>  $user_notif,
                        'section_comment' => $this->translate('notifications for Users'),
                        'section' => 'user',
                        'sub_sections' => array(
                          array(
                            'item_type' => 'user',
                            'item_notifications' => array_filter($user_notif, function($i) {
                                                      if($i['not_type'] == 'new_user_add') return true;
                                                      return false;
                                                    }),
                            'item_header_icon' => 'fa fa-users text-aqua',
                            'item_header_text' => $this->translate('new members added to database'),
                            ),
                          array(
                            'item_type' => 'user',
                            'item_notifications' => array_filter($user_notif, function($i) {
                                                      if($i['not_type'] == 'new_user_reg') return true;
                                                      return false;
                                                    }),
                            'item_header_icon' => 'fa fa-users text-aqua',
                            'item_header_text' => $this->translate('new users registered'),
                            )

                          )
                       )
                );?>

                <?php  $cv_notif = $this->notifications()->cv;?>
                <?=$this->partial(
                  'admin/partial/menu-notifications.phtml', 
                  array(
                        'menu_icon' => 'fa fa-file-text-o',
                        'section_notifications' =>  $cv_notif,
                        'section_comment' => $this->translate('notifications for CV'),
                        'section' => 'cv',
                        'sub_sections' => array(
                          array(
                            'item_type' => 'user',
                            'item_notifications' => array_filter($cv_notif, function($i) {
                                                      if($i['not_type'] == 'cv_uploaded') return true;
                                                      return false;
                                                    }),
                            'item_header_icon' => 'fa fa-file-text-o',
                            'item_header_text' => $this->translate('new cv uploaded'),
                            ),
                          array(
                            'item_type' => 'user',
                            'item_notifications' => array_filter($cv_notif, function($i) {
                                                      if($i['not_type'] == 'cv_edit') return true;
                                                      return false;
                                                    }),
                            'item_header_icon' => 'fa fa-file-text-o',
                            'item_header_text' => $this->translate('user cv information edited'),
                            ),

                          )
                       )
                );?>
              <?php endif ?>
              <?php if ($this->isPermitted('admin\controller\userdb.company')): ?>
              <?php  $company_notif = $this->notifications()->company;?>
              <?=$this->partial(
                'admin/partial/menu-notifications.phtml', 
                array(
                      'menu_icon' => 'fa fa-university',
                      'section_notifications' =>  $company_notif,
                      'section_comment' => $this->translate('notifications for Companies'),
                      'section' => 'company',
                      'sub_sections' => array(
                        array(
                          'item_type' => 'company',
                          'item_notifications' => array_filter($company_notif, function($i) {
                                                    if($i['not_type'] == 'new_company_add') return true;
                                                    return false;
                                                  }),
                          'item_header_icon' => 'fa fa-university text-aqua',
                          'item_header_text' => $this->translate('new company added to database'),
                          ),
                        array(
                          'item_type' => 'company',
                          'item_notifications' => array_filter($company_notif, function($i) {
                                                    if($i['not_type'] == 'new_company_reg') return true;
                                                    return false;
                                                  }),
                          'item_header_icon' => 'fa fa-university-aqua',
                          'item_header_text' => $this->translate('new company registered'),
                          ),
                        array(
                          'item_type' => 'company',
                          'item_notifications' => array_filter($company_notif, function($i) {
                                                    if($i['not_type'] == 'add_company_user') return true;
                                                    return false;
                                                  }),
                          'item_header_icon' => 'fa fa-unlock',
                          'item_header_text' => $this->translate('users info unlocked'),
                          ),
                        array(
                          'item_type' => 'user',
                          'item_notifications' => array_filter($company_notif, function($i) {
                                                    if($i['not_type'] == \Application\Model\AdminNotifTable::NOT_TYPE_COMPANY_NOTE) return true;
                                                    return false;
                                                  }),
                          'item_header_icon' => 'fa fa-pencil-square-o',
                          'item_header_text' => $this->translate('cv notes added'),
                          )


                        )
                     )
              );?>
              <?php endif ?>

              <!-- Tasks Menu -->
<!--               <li class="dropdown tasks-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-flag-o"></i>
                  <span class="label label-danger">9</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 9 tasks</li>
                  <li>
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <h3>
                            Design some buttons
                            <small class="pull-right">20%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">20% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li>                     
                    </ul>
                  </li>
                  <li class="footer">
                    <a href="#">View all tasks</a>
                  </li>
                </ul>
              </li> -->

              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="<?= $this->basePath('/'._PICSWWW_.$this->identity()->avatar); ?>" class="user-image" alt="User Image"/>
                  <span class="hidden-xs"><?= $this->identity()->name.' '.$this->identity()->surname; ?></span>
                </a>
                <ul class="dropdown-menu">
                  <li class="user-header">
                    <img src="<?= $this->basePath('/'._PICSWWW_.$this->identity()->avatar); ?>" class="img-circle" alt="User Image" />
                    <p>
                      <?= $this->identity()->name.' '.$this->identity()->surname; ?>
                      <small><?=ucfirst($this->identity()->role);?></small>
                    </p>
                  </li>
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat"><?=$this->translate('Settings');?></a>
                    </div>
                    <div class="pull-right">
                      <a href="<?=$this->url('admin/exit');?>" class="btn btn-default btn-flat"><?=$this->translate('Sign out');?></a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
  
          <!-- Sidebar user panel (optional) -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="<?=_ADDRESS_._PICSWWW_.$this->identity()->avatar; ?>" class="img-circle" alt="<?= $this->identity()->name.' '.$this->identity()->surname; ?>" />
            </div>
            <div class="pull-left info">
              <p><?= $this->identity()->name.' '.$this->identity()->surname; ?></p>
              <!-- Status -->
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>

        <?php

        $this->navigation('navigation')->setRole($this->identity()->role);
        $this->navigation('admin_nav')->setMaxDepth(3);
        echo $this->navigation('admin_nav')
            ->menu()
            ->setUlClass('sidebar-menu')
            ->setPartial('partial/navigation-bootstrap-3/navigation_admin.phtml');

        ?>

        <?php
        if($this->siteInfo()->identity) {?>
        <hr />
                <div class="col-sm-12">
                    <?php $this->siteInfo()->updateAdminActivity();?>
                    <?php $online_admins = $this->siteInfo()->online_admins;?>
                    
                    <?php if(count($online_admins) > 0)  { ?>
                        <h5 class="text-info">
                          <?=$this->translate('Admins Online');?> (<?=count($online_admins);?>)
                        </h5>
                        <?php foreach ($online_admins as $admin) :?>
                            <div class="row friend_item">
                                <div class="col-sm-3 text-right avatar">
                                    <a href="<?=_ADDRESS_.zgetUserLogin($admin);?>">
                                        <img src="<?=zgetUserAvatar($admin);?>" class="img-circle" width="35" height="35"/>
                                    </a>
                                </div>
                                <div class="col-sm-9 text-left name">
                                    <h5>
                                      <a href="<?=_ADDRESS_.zgetUserLogin($admin);?>"><?=zgetUserName($admin);?></a> <br />
                                      <small><?=$admin->role;?></small>
                                    </h5>

                                </div>
                            </div>
                        <?php endforeach ?>
                    <?php } ?>

                </div>
                <hr />
        <?php } ?>
  
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
              <div class="row">
                    <?php if ($this->pageHeader): ?>
                      <h1>
                        <?= $this->pageHeader; ?>
                      </h1>
                    <?php else: ?>
                      <?php
                         echo $this->navigation('navigation')
                                  ->breadcrumbs()
                                  ->setMinDepth(0)
                                  ->setMaxDepth(3)
                                  ->setRole($this->identity()->role)
                                  ->setPartial('partial/admin_breadcrumb.phtml');
                      ?>
                      <?php if ($this->pageDescription): ?>
                        <?=$this->pageDescription;?>
                      <?php endif ?>
                    <?php endif ?>
              </div>
        </section>

        <!-- Main content -->
        <section class="content pt10">
          

          <!-- Your Page Content Here -->
          <?= $this->content; ?>

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
          .
        </div>
        <!-- Default to the left --> 
        <strong>Copyright &copy; 2015 <a href="<?=_ADDRESS_;?>">SEACONTACT.COM</a>.</strong> All rights reserved.
      </footer>

    </div><!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    
    <!-- AdminLTE App -->
    <?= $this->inlineScript()
        // ->prependFile($this->basePath('js/admin-app.js'))
    ; ?>
    <script type="text/javascript">

      $('select:not(.no_chosen)').chosen({
        disable_search_threshold: 10,
        search_contains: 1
      });


      <?php if($this->flashMessenger()->hasCurrentSuccessMessages()) :?>
        $.notify({
          message: '<?=zstripNl(addslashes($this->flashMessenger()->renderCurrent("success")));?>' 
        },notify_success_settings);
        <?php $this->flashMessenger()->clearCurrentMessages('success');?>
      <?php endif ?>

      <?php if($this->flashMessenger()->hasSuccessMessages()) :?>
        $.notify({
          message: '<?=zstripNl(addslashes($this->flashMessenger()->render("success")));?>' 
        },notify_success_settings);
      <?php endif ?>

      <?php if($this->flashMessenger()->hasCurrentErrorMessages()) :?>
        $.notify({
          message: '<?=zstripNl(addslashes($this->flashMessenger()->renderCurrent("error")));?>' 
        },notify_error_settings);
        <?php $this->flashMessenger()->clearCurrentMessages('error');?>
      <?php endif ?>

      <?php if($this->flashMessenger()->hasErrorMessages()) :?>
        $.notify({
          message: '<?=zstripNl(addslashes($this->flashMessenger()->render("error")));?>' 
        },notify_error_settings);
      <?php endif ?>

    // $(document).ready( function() {
    //       $.get('/mailbox/refresh-mailbox',null, function(response) {
    //         console.log(response.data);
    //       }, 'json');
    //   });


      $('.clear_notif').click(function(e){
        e.preventDefault();
        var container = $(this).parents('.dropdown');
        var section = container.data('section');
        $.get('/index/read-notification',{section: section}, function(response) {
          if(response.success) {
            container.find('.not_label').remove();
            container.find('.notification_item').remove();
            container.find('.not_count').text('0');
          } else $.notify({message: response.message },notify_error_settings);
        }, 'json');
      });

    </script>
  </body>
</html>