
<section id ="cv-delete" class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-9">
					<h2>Delete</h2>
				</div>
			</div>

			<!-- Modal -->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog modal-sm">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h2 class="modal-title" id="myModalLabel"><?=$this->modal_header;?></h2>
			      </div>
			      <div class="modal-body">
			      	<div class="container-fluid">
			      		<div class="row">
			      			<h3> Are you sure want to delete ? </h3>
			      		</div><!-- row -->
			      	</div><!-- container-fluid -->


			      </div><!-- modal-body -->


			      <div class="modal-footer">
					<?php
						$form = $this->form;
						$form->prepare();
						$form->setAttribute('class', 'col-md-12');
						$form->setAttribute('id', 'delete_confirm');
						echo $this->form(null)->openTag($form);
					?>
					<?=$this->formButton($form->get('cancel')
						->setOptions(array(
							'glyphicon' => array(
								'icon' => 'remove',
								'position' => 'append',
								),
							))
						->setAttribute('class', 'btn-primary'));
					?>			        
					<?=$this->formButton($form->get('delete')
						->setOptions(array(
							'glyphicon' => array(
								'icon' => 'trash',
								'position' => 'append',
								),
							))
						->setAttribute('class', 'btn-default'));
					?>
					<?= $this->form()->closeTag();?>
			      </div><!-- modal-footer -->
			    </div>
			  </div>
			</div>

		</div> <!-- section col-sm-12 -->
	</div> <!-- row -->
</section>

<script type="text/javascript">
	<?php 
	if(true === $this->show_form) { ?>

	    $(window).load(function(){
	        $('#myModal').modal('show');
	    });

	<?php }?>

	$('#myModal').on('shown.bs.modal', function () {
	  $('#myInput').focus();
	  $('.modal-backdrop').remove();
	});

</script>