<?= $this->doctype(); ?>
<html lang="en">
  <head>

	  <?= $this->headTitle('SEACONTACT '. $this->translate('WELCOME'))->setSeparator(' - ')->setAutoEscape(false) ?>
		<meta charset="utf-8">
		<meta name="description" content="worldwide seafarers community " />
		<meta name="author" content="z_loy" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
		    ->prependStylesheet('/css/landing/camera.css')
		    ->prependStylesheet('/css/landing/slicknav.css')
		    ->prependStylesheet('/css/landing/prettyPhoto.css')
		    ->prependStylesheet('/css/landing/style.css'._SCRIPTS_VER_)
		    ->prependStylesheet('/css/fonts/font-awesome/css/font-awesome.css')
		    // ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:400,300,700|Open+Sans:700')
		    ->prependStylesheet('/vendor/twbs/bootstrap/dist/css/bootstrap.min.css')

			->appendStylesheet('/vendor/chosen/chosen.min.css')

		    ->appendStylesheet('/css/content-main-default.css'._SCRIPTS_VER_)

		;?>

	    <?= $this->headStyle();?>
	    <?= $this->headScript()
	    // if jquery < 2.1.3 need to manually add bootstrap extensions
	    ->prependFile($this->basePath('/vendor/twbs/bootstrap/js/modal.js'))
	    ->prependFile($this->basePath('/vendor/twbs/bootstrap/js/popover.js'))
	    ->prependFile($this->basePath('/vendor/twbs/bootstrap/js/tooltip.js'))
	    // ->prependFile($this->basePath('/js/landing/sorting.js')) // what is it ?
	    // ->prependFile($this->basePath('/js/landing/jquery.isotope.js')) // what is it ?
	    ->prependFile($this->basePath('/js/landing/jquery.nav.js'))
	    // ->prependFile($this->basePath('/js/landing/jquery.prettyPhoto.js')) // what is it ?
	    ->prependFile($this->basePath('/js/landing/jquery.mobile.customized.min.js'))
	    ->prependFile($this->basePath('/js/landing/jquery.easing.1.3.js'))
	    ->prependFile($this->basePath('/js/landing/jquery.slicknav.js'))
	    ->prependFile($this->basePath('/js/landing/camera.min.js'))
	    ->prependFile($this->basePath('/js/jquery-1.8.3.js'))
	    ->prependFile($this->basePath('/vendor/twbs/bootstrap/dist/js/bootstrap.min.js'))
	    ->prependFile($this->basePath('/js/jquery-2.1.3.min.js'))
	    
	    ->appendFile('/vendor/bootstrap-notify/bootstrap-notify.min.js')
 		->appendFile('/vendor/chosen/chosen.jquery.min.js')

	    ->appendFile($this->basePath('/js/main.js'._SCRIPTS_VER_))
	    ->appendFile($this->basePath('/js/landing/landing.js'))
	    ;?>
	    <script type="text/javascript" src="http://platform.linkedin.com/in.js">
	    	api_key:   77z0oq1xmbw13v
	    	authorize: true
	    	lang: en_US
	    </script>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-68597581-1', 'auto');
		  ga('send', 'pageview');

		</script>

	</head>
	<body>
    	<div id="vk_api_transport"></div>
		<div id="main-content">
			<?=$this->content;?>
		</div>
	    
	    <div id="footer">
			<div class="lineBlack">
				<div class="container">
					<div class="row downLine">
						<!-- 
							<div class="col-md-12 text-right">
								<input  id="searchPattern" type="search" placeholder="Search the Site"/><i class="glyphicon glyphicon-search" style="font-size: 13px; color:#a5a5a5;" id="iS"></i>
							</div>
						 -->
						<div class="col-md-6 text-left copy">
							<p>Copyright &copy; 2015 Seacontact.com . All Rights Reserved </p>
						</div>
						<div class="col-md-6 text-right dm">
							<ul id="downMenu">
								<li class="active" ><a href="<?=$this->url('sc/home', array(), array('fragment' => 'home'));?>"><?=$this->translate('Home');?></a></li>
		                        <li><a href="<?=$this->url('sc/home', array(), array('fragment' => 'vacancies'));?>"><?=$this->translate('Vacancies');?></a></li>
		                        <li><a href="<?=$this->url('sc/home', array(), array('fragment' => 'cvs'));?>"><?=$this->translate('CV\'s');?></a></li>
		                        <li><a href="<?=$this->url('sc/home', array(), array('fragment' => 'news'));?>"><?=$this->translate('News');?></a></li>
		                        <li><a href="<?=$this->url('sc/home', array(), array('fragment' => 'contacts'));?>"><?=$this->translate('Contacts');?></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
	    </div>		
		
	    <?= $this->inlineScript()
	        // ->prependFile($this->basePath('/js/landing/landing.js'))
	    ;?>		
	    <script type="text/javascript">
		    $('select').chosen({
		        disable_search_threshold: 10,
		        search_contains: 1
		    });
	    </script>
	    <script>
	    	window.fbAsyncInit = function() {
	    		FB.init({
	    			appId      : '956454421068622',
	    			xfbml      : true,
	    			version    : 'v2.5'
	    		});
	    	};

	    	(function(d, s, id){
	    		var js, fjs = d.getElementsByTagName(s)[0];
	    		if (d.getElementById(id)) {return;}
	    		js = d.createElement(s); js.id = id;
	    		js.src = "//connect.facebook.net/en_US/sdk.js";
	    		fjs.parentNode.insertBefore(js, fjs);
	    	}(document, 'script', 'facebook-jssdk'));



	    	/* --------------- Vkontakte -------------------*/

	    	window.vkAsyncInit = function() {
	    		VK.init({
	    			apiId: 5148062,
	    			onlyWidgets: false
	    		});
	    	};

	    	setTimeout(function() {
	    		var el = document.createElement("script");
	    		el.type = "text/javascript";
	    		el.src = "//vk.com/js/api/openapi.js";
	    		el.async = true;
	    		document.getElementById("vk_api_transport").appendChild(el);
	    	}, 0);
	    	

	    	<?php if($this->flashMessenger()->hasCurrentSuccessMessages()) :?>
	    		$.notify({
	    			message: '<?=zstripNl(addslashes($this->flashMessenger()->renderCurrent("success")));?>' 
	    		},notify_success_settings);
	    		<?php $this->flashMessenger()->clearCurrentMessages('success');?>
	    	<?php endif ?>
	    	<?php if($this->flashMessenger()->hasSuccessMessages()) :?>
	    		$.notify({
	    			message: '<?=zstripNl(addslashes($this->flashMessenger()->render("success")));?>' 
	    		},notify_success_settings);
	    	<?php endif ?>
	    	<?php if($this->flashMessenger()->hasCurrentErrorMessages()) :?>
	    		$.notify({
	    			message: '<?=zstripNl(addslashes($this->flashMessenger()->renderCurrent("error")));?>' 
	    		},notify_error_settings);
	    		<?php $this->flashMessenger()->clearCurrentMessages('error');?>
	    	<?php endif ?>
	    	<?php if($this->flashMessenger()->hasErrorMessages()) :?>
	    		$.notify({
	    			message: '<?=zstripNl(addslashes($this->flashMessenger()->render("error")));?>' 
	    		},notify_error_settings);
	    	<?php endif ?>

	    </script>
	</body>
	
</html>