<div class="vk_publics_form">
	<?php
		$form = $this->form;
		$form->prepare();
		$form->setAttribute('class', 'form-horizontal');
		$fieldset = $form->get('parsing_options');
		echo $this->form()->openTag($form);
	?>
	<div class="form-group">
		<div class="col-md-12">
			<?=$this->formLabel($fieldset->get('page'));?>
			<?=$this->formElement($fieldset->get('page')->setAttribute('class', 'form-control input-sm '));?>
			<?=$this->formElementErrors($fieldset->get('page'));?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-12">
			<?=$this->formButton()->openTag($form->get('submit')->setAttribute('class', 'btn btn-success form-control input-sm'));?>
				<span class="fa fa-plus"></span> 
	 			 <?=$form->get('submit')->getLabel();?>
			<?=$this->formButton()->closeTag();?>
		</div>
	</div>

	<?= $this->form()->closeTag();?>
</div>

