<div id="home">
    <div class="headerLine">
        <?= $this->partial('landing-menu');?>
        <div class="container">
            <div class="row footer">
                <div class="col-md-12">
                    <h3><?=$this->translate('Confirm Reset Password');?></h3>
                    <div class="fr">
                        <div style="display: inline-block;">
                            <?php
                                $form = $this->form;
                                $form->prepare();
                                echo $this->form()->openTag($form);
                            ?>
                                <?=$this->formElement($this->form->get('user')->get('password_reset_key')->setAttributes(array(
                                    'id' => 'password_reset_key', 'class' => 'col-md-6 fEmail'))); ?>
                                <?=$this->formElement($this->form->get('submit')->setAttribute('class', 'subS')); ?>
                                <div id="captcha-field">
                                    <?php if($this->form->has('captcha')) {
                                        echo $this->formCaptcha($this->form->get('captcha'));
                                    }?>
                                </div>                
                            <?=$this->form()->closeTag();?>
                            <div class="system-messages">
                                <?php if($this->msgs()) { ?>
                                    <script type="text/javascript">
                                        $(window).load(function(){
                                            $('#myModal').modal('show');
                                        });
                                    </script>
                                <?php }?>
                            </div>
                        </div>
                    </div>
                </div>
                <?=$this->partial('landing-social');?>
            </div>
        </div>
    </div>

    <div class="modal fade" id="myModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal"><?=$this->translate('Ok');?></button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <script type="text/javascript">

        $('#myModal').on('shown.bs.modal', function () {
            $('.modal-body').html('<?=$this->msgs();?>');
            $('#myInput').focus();
            $('.modal-backdrop').remove();
        });

    </script>
</div>
