<div id="home">
    <div class="headerLine">
        <?= $this->partial('landing-menu');?>
        <div class="container">
            <div class="row footer">
                <div class="col-md-12">
                    <h3><?=$this->translate('Remind Password');?></h3>
                    <div class="fr">
                        <span id="helpBlock" class="help-block bg-info"><?=$this->translate('Please enter your email and we will send you a new password');?></span>
                        <div style="display: inline-block;" aria-describedby = 'helpBlock'>
                            <?php
                            $form = $this->form;
                            $form->prepare();
                            echo $this->form()->openTag($form);
                                // echo $this->formElement($this->form->get('csrf'));
                            ?>
                            <?=$this->formElement($this->form->get('user')->get('email')->setAttributes(array('id' => 'reg_email', 'class' => 'col-md-6 fEmail'))); ?>
                            <?=$this->formSubmit($this->form->get('submit')->setAttribute('class', 'subS')); ?>
                            <div id="captcha-field">
                                <?php if($this->form->has('captcha')) {
                                    echo $this->formCaptcha($this->form->get('captcha'));
                                }?>
                            </div>                
                            <?=$this->form()->closeTag();?>
                            <div class="system-messages">
                                <?= $this->msgs();?>
                            </div>
                        </div>
                    </div>
                </div>
                <?=$this->partial('landing-social');?>
            </div>
        </div>
    </div>
</div>
