<div id="home" class="auth_page">
    <div class="headerLine">
        <?= $this->partial('landing-menu');?>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3><?=$this->translate('Enter new password');?></h3>
                    <div class="fr">
                        <div style="display: inline-block;">
                            <?php
                                $form = $this->form;
                                $form->prepare();
                                $form->setAttribute('class', 'form-horizontal');
                                echo $this->form()->openTag($form);
                            ?>
                            <?=$this->formElement($this->form->get('user')->get('password_reset_key')->setAttributes(array(
                            'id' => 'password_reset_key','type' => 'hidden', 'class' => 'password_reset_key'))); ?>
                                <div class="form-group">   
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?=$this->formElement($this->form->get('user')->get('password')->setAttributes(array('class' => 'form-control fEmail'))); ?>
                                                
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?=$this->formElement($this->form->get('user')->get('confirm_password')->setAttributes(array('class' => 'fEmail form-control'))); ?>
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <?=$this->formSubmit($this->form->get('submit')->setAttribute('class', 'form-control subS')); ?>
                                    </div>
                                    <div id="captcha-field" class="form-group">
                                        <?php if($this->form->has('captcha')) {?>
                                            <div class="col-md-12">
                                                <?= $this->formElement($this->form->get('captcha'));?>
                                            </div>
                                        <?php }?>
                                    </div> 
                                </div>               
                            <?=$this->form()->closeTag();?>
                            <div class="system-messages">
                                <?= $this->msgs();?>
                            </div>
                        </div>
                    </div>
                </div>
                <?=$this->partial('landing-social');?>
            </div>
        </div>
    </div>
</div>
