<div id="home" class="auth_page">
    <div class="headerLine">
        <?= $this->partial('landing-menu');?>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 style="margin-top: 80px;"><?=$this->translate('Registration through Social Networks');?></h3>
                    <div class="fr">
                        <div style="display: inline-block;">
                            <div class="form-horizontal">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="alert alert-success">
                                            <p>
                                                <ul class="text-left">
                                                    <li><?=$this->translate('We have a very large database of seamans CVs');?></li><br />
                                                    <li><?=$this->translate('We need your <b>E-mail</b> to check, maybe your CV is already there, and you only need to update it');?></li><br />
                                                    <li><?=$this->translate('Please confirm access to <b>E-mail</b> during registration');?></li><br />
                                                 </ul>
                                            </p>

                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-6 col-md-offset-3 text-center">
                                        <span class="help-block bg-warning pt pb">
                                            <h5 class="mb0 mt0"><a href="<?=$this->url('sc/social_auth');?>"><?=$this->translate('Login with social networks');?></a></h5>
                                            <?=$this->partial('application/partial/auth-social-links');?>
                                        </span>
                                    </div>
                                </div> 
                                <?php if ($this->msgs()): ?>
                                    <div class="form-group">
                                        <div class="col-md-12 text-center">
                                            <div class="system-messages">
                                                <?= $this->msgs();?>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?=$this->partial('landing-social');?>
            </div>
        </div>
    </div>
</div>