<!DOCTYPE html>
<html lang="en">
	<head>
		<?= $this->headLink()
			->prependStylesheet('/vendor/twbs/bootstrap/dist/css/bootstrap.min.css')
			->appendStylesheet('/css/content-main-default.css')
			->appendStylesheet('/css/content-main.css')
		;?>
		<?= 
			$this->headScript()
			->prependFile($this->basePath('/vendor/twbs/bootstrap/dist/js/bootstrap.min.js'))
			->prependFile($this->basePath('/js/jquery-2.1.3.min.js'))

		;?>
	</head>
	<body id="frame-body">
		<section id="pm-flow" class="container-fluid">
			<div class="msg-list row">
					<?php foreach($messages as $message) :?>
					<?php if($message['from_id'] != $from_id) { ?>
						<div class="msg msg-in col-sm-9 col-xs-12">
							<div class="row">
								<div class="col-sm-2 col-sm-2">
									<div class="row">
										<div class="msg-user col-sm-12 col-sm-12 text-center">
											<a href="<?=$this->basePath(zgetUserLogin($message, 'from_'))?>" target="_parent">
												<img src="<?=zgetUserAvatar($message, 'from_');?>" />
											</a>
											<span class="msg-user-name">
												<a href="<?=$this->basePath(zgetUserLogin($message, 'from_'))?>" target="_parent">
													<?=zhashUserName(zgetUserName($message, 'from_'), 0, $this->isPermitted('_user_fields\name', $message['from_id']));?>
												</a>
											</span>
										</div> <!-- msg-user col-sm-2 -->
									</div>
								</div>
								<div class="col-sm-9" >
									<div class="msg-text row">
										<div class="col-sm-12 col-sm-12">
											<?php echo htmlspecialchars_decode($message['text']);?>
										</div>
									</div> <!-- msg row -->
									<div class="row">
										<div class="msg-time col-sm-3 col-sm-3">
											<?php echo zformatDateTime($message['time']);?>
										</div>
									</div>
								</div>
<!-- 								<div class="msg-delete col-sm-1">
									<a href="<?= $this->url(NULL, array(
										'controller' => 'messages',
										'action' => 'delete',
										'id' => $message['message_id'])); ?>" target="_parent"><span class="fa fa-times-circle"></span>
									</a>
								</div> -->								
							</div>
						</div>
					<?php } else { ?>
						<div class="msg msg-out col-sm-offset-3 col-sm-9 col-xs-12">
							<div class="row">
								<div class="msg-delete col-sm-1 col-sm-1">
									<a href="<?= $this->url(NULL, array(
										'controller' => 'messages',
										'action' => 'delete',
										'id' => $message['message_id'])); ?>" target="_parent"><span class="fa fa-times-circle"></span>
									</a>
								</div>
								<div class="col-sm-9 ">
									<div class="msg-text row">
										<div class="col-sm-12 col-sm-12">
											<?php echo htmlspecialchars_decode($message['text']);?>
										</div>
									</div> <!-- msg row -->
									<div class="row">
										<div class="msg-time col-sm-offset-9 col-sm-3 col-sm-3">
											<?php echo zformatDateTime($message['time']);?>
										</div>
									</div>
								</div>
								<div class="col-sm-2 col-sm-2">
									<div class="row">
										<div class="msg-user col-sm-12 col-sm-12">
											<img src="<?=zgetUserAvatar($message, 'from_');?>" />
											<!-- <span class="msg-user-name">
												<a href="<?=$this->basePath($message['from_login'])?>" target="_parent">
													<?=$this->escapeHtml($message['from_name']);?>
												</a>
											</span> -->
										</div> <!-- msg-user col-sm-2 -->
									</div>
								</div>								
							</div>
						</div>
					<?php } ?>

					<?php endforeach;?>					
			</div>

		</section>
	

	<script type="text/javascript">
		<?php if (count($messages) > 0): ?>
			$('html, body').animate({scrollTop:$('div.msg:last').offset().top}, 0);
		<?php endif ?>
		
	</script>		
	</body>
</html>
