<section class="ships-contracts">
	<h2> Contract on <?=$ship_name; ?> </h2>

	<?php
		$form = $this->form;
		$form->prepare();
		$form->setAttribute('action', 
			$this->url(NULL, array(
				'controller' => 'contracts',
				'action' => 'edit',
				'id' => $contract_id,
				))
			);
		echo $this->form()->openTag($form);

	?>
	<div class="form-element">
		<?php
			$collection = $form->get('contract');
			echo $this->formCollection($collection);
			$fileElement = $form->get('pics');
			echo $this->formLabel($fileElement);
			echo $this->formFile($fileElement);
			echo $this->formElementErrors($fileElement);
			$old_pics = $form->get('old_pics');
			echo $this->formLabel($old_pics);
			echo '<br />';
			$old_pics = $old_pics->getElements();

			foreach ($old_pics as $pic) { ?>
					<img src="<?= '/'._PICSWWW_.$pic->getAttribute('data-thumb'); ?>" /> 
			<?php
				echo $this->formElement($pic);
			}
			echo '<br />';

			// echo $this->formElement($form->get('csrf'));
			echo $this->formElement($form->get('submit'));
			echo $this->form()->closeTag();
		?>
	</div>


<hr style="clear: both;">
<a href="<?= $this->url('contracts'); ?>">Back</a>
</section>