<section class="container-fluid">
<div class="row">
	<div class="col-md-12">
		<?php
			$form = $this->form;
			$form->prepare();
			$form->setAttribute('class', 'form-horizontal');
			$fieldset = $form->get('vacancy_candidates');
			echo $this->form()->openTag($form);
		?>
			<div class="form-group">
				<div class="col-md-2 text-left">
					<img src="<?=_ADDRESS_NO_SLASH_.'/'.zgetUserCvAvatar($user); ?>" class="img-responsive"/>
				</div>
				<div class="col-md-2">
					<h4><?=zgetUserName($user);?></h4>
					<?=$this->translate('Position Applied For');?>:
					<h4><?=$user->desired_rank;?></h4>
				</div>
				<div class="col-md-5">
					<?=$this->formLabel($fieldset->get('comments'));?>
					<?=$this->formElement($fieldset->get('comments')->setAttribute('class','form-control'));?>
					<?=$this->formElementErrors($fieldset->get('comments'));?>
				</div>
				<div class="col-md-3">
					<?=$this->formLabel($fieldset->get('status'));?>
					<?=$this->formElement($fieldset->get('status')->setAttribute('class','form-control'));?>
					<?=$this->formElementErrors($fieldset->get('status'));?>
				</div>
			</div>
			<div class="form-group">
				<?=$this->partial('admin/partial/vacancy-table',array(
					'title' => $this->translate('For Vacancy').' :',
					'vacancies' => $active_vacancies,
					'radio_buttons' => 1,
					'fields' => ['edit', 'title', 'comments', 'rank', 'salary', 'ship_type', 'publish_time']
				));?>
				<?=$this->formElementErrors($fieldset->get('vacancy'));?>
			</div>

			<div class="form-group">
				<div class="col-md-12">
					<?=$this->formButton()->openTag($form->get('submit')->setAttribute('class', 'btn btn-success form-control input-lg'));?>
						<span class="fa fa-user-plus"></span> 
			 			 <?=$form->get('submit')->getLabel();?> 
					<?=$this->formButton()->closeTag();?>
				</div>
			</div>

		<?= $this->form()->closeTag();?>		
	</div>
</div>

<div class="row pt mt">
	<?=$this->partial('admin/partial/vacancy-table',array(
		'title' => $this->translate('Already Assigned To Vacancies'),
		'vacancies' => $candidate_vacancies,
		'user_id' => $user->user_id,
		'fields' => ['edit', 'title', 'comments', 'rank', 'salary', 'ship_type', 'publish_time', 'candidate_status', 'candidate_assigned_date']
	));?>
</div>

</section>