<div class="row">
	<div class="col-md-12 ">
		<div class="box">
			<div class="box-header bg-info">
				<div class="row">
					<div class="col-md-3">
						<h4><?= $this->translate('Vacancy Candidates');?></h4>
					</div>
					<div class="col-md-9">
						<?php 
							$status_list = \Application\Model\VacancyCandidatesTable::getCandidateStatusList();
							foreach($status_list as $key => $status) {
								$filters_list[] = ['name' => 'status', 'value' => $key, 'title' => $status]; 
							}
						?>
						<?=$this->partial('application/partial/custom_horiz_filters', ['filters' => $q_options['filters'], 'filters_list' => $filters_list, 'show_all_btn' => 0]);?>
					</div>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-md-12 table-responsive">
						<?=$this->partial('admin/partial/users-table');?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12 text-center custom_pagination">
		<?=$this->partial('application/partial/custom_pagination');?>
	</div>
</div>