<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<?php 
				$form = $this->form;
				$form->prepare();
				$form->setAttribute('class', 'form-horizontal');
				echo $this->form(null)->openTag($form);
			?>

			<div class="form-group">
				<?=$this->formElement($form->get('user_id'));?>
				<div class="row">
					<div class="col-md-8">
						<?=$this->formLabel($form->get('company_id'));?>
						<?=$this->formElement($form->get('company_id')->setAttribute('class','form-control'));?>
						<?=$this->formElementErrors($form->get('company_id'));?>
					</div>		
					<div class="col-md-4">
						<?=$this->formLabel($form->get('submit'));?>
						<?=$this->formButton()->openTag($form->get('submit')->setAttribute('class', 'btn btn-primary form-control'));?>
							<span class="glyphicon glyphicon-send"></span>
							<?=$this->translate('Add');?>
						<?=$this->formButton()->closeTag($form);?>
					</div>
				</div>


			</div>
			<?=$this->form()->closeTag();?>				
		</div>
	</div>	
	<div class="row mt pt">
		<div class="col-md-12 table-responsive">
			<div class="box">
				<div class="box-header bg-info">
					<div class="row">
						<div class="col-md-12">
							<h4><?= $this->translate('Worked for companies');?> : <small><b><?=$total_results;?></b></small></h4>
						</div>
					</div>
				</div>
				<div class="box-body">
					<?=$this->partial('admin/partial/users-table');?>
				</div>
				<div class="box-footer">
					<div class="row">
						<div class="col-md-12 text-center">
							<?=$this->partial('application/partial/custom_pagination');?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>






