<section class="container-fluid">
	<?php
		$form = $this->form;
		$form->prepare();
		$fieldset = $form->get('user');
		echo $this->form()->openTag($form);
	?>

		<div class="row">
			<div class="col-sm-6">
				<div class="panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading text-center"><h4><?=$this->translate('Hide fields');?> :</h4></div>
				  <!-- List group -->
				  <ul class="list-group">
					  <?php foreach ($fieldset as $field): ?>
					  		<li class="list-group-item">
					  			<div class="btn-group" role="group">
					  			  <button type="button" class="btn btn-default"><?=$this->formCheckbox($field);?></button>
					  			</div>
					  			<div class="btn-group pl" role="group">
					  				<?=$this->formLabel($field);?>
					  			</div>
						  		<?=$this->formElementErrors($field);?>
					  		</li>

					  <?php endforeach ?>
				  </ul>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading text-center"><h4><?=$this->translate('Language');?> :</h4></div>
				  <!-- List group -->
				  <ul class="list-group">
				  		<li class="list-group-item">
				  			<?=$this->formRadio($form->get('lang')->setAttribute('style','margin-left: 10px;margin-right: 5px;'));?>
					  		<?=$this->formElementErrors($form->get('lang'));?>
				  		</li>
				  </ul>
				</div>
			</div>
			<div class="col-sm-12">
				<?=$this->formButton()->openTag($form->get('submit')->setAttribute('class', 'btn btn-success form-control input-sm'));?>
					<span class="glyphicon glyphicon-floppy-save"></span> 
		 			 <?=$form->get('submit')->getLabel();?> 
				<?=$this->formButton()->closeTag();?>
			</div>
		</div>

	<?= $this->form()->closeTag();?>
</section>